# Generated by Django 3.2.8 on 2021-10-13 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_profile_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('pubDate', models.DateField(null=True)),
                ('link', models.CharField(max_length=500)),
                ('feed', models.CharField(max_length=500)),
                ('subscriber', models.ManyToManyField(to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sniptitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info_app.feeds')),
                ('subscriber', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
