# Generated by Django 3.2.8 on 2021-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0002_auto_20211008_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalregister',
            name='pubDate',
            field=models.DateField(null=True),
        ),
    ]
